<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nUr2Iyx' shared service.

return $this->privates['.service_locator.nUr2Iyx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ContactController::contact' => ['privates', '.service_locator.QdSwBri', 'get_ServiceLocator_QdSwBriService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\ContactController:contact' => ['privates', '.service_locator.QdSwBri', 'get_ServiceLocator_QdSwBriService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
], [
    'App\\Controller\\ContactController::contact' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\ContactController:contact' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
