<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMTKHGTy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMTKHGTy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMTKHGTy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMTKHGTy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMTKHGTy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MTKHGTy',
    'container.build_id' => '315c393b',
    'container.build_time' => 1580044277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMTKHGTy');
